version: "3.9"

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

volumes:
  mongo-data:
